apiVersion: v1
kind: Service
metadata:
  name: __SERVICE_NAME__
  labels:
    app: __SERVICE_NAME__
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: __SERVICE_NAME__
  selector:
    app: __SERVICE_NAME__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __SERVICE_NAME__
  labels:
    app: __SERVICE_NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __SERVICE_NAME__
  template:
    metadata:
      labels:
        app: __SERVICE_NAME__
    spec:
      containers:
        - name: __SERVICE_NAME__
          image: __IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080