apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  labels:
    app: SERVICE_NAME
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: SERVICE_NAME
  selector:
    app: SERVICE_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME
  labels:
    app: SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE_NAME
  template:
    metadata:
      labels:
        app: SERVICE_NAME
    spec:
      containers:
        - name: SERVICE_NAME
          image: __IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080